{
 "title": "Dashboard 2025",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Hard memory",
   "type": "timeseries",
   "description": "Место на файловой системе",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory OZU",
   "type": "timeseries",
   "description": "Опративная память",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Нагрузка на процессор",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_load5{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_load15{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilisation CPU",
   "type": "timeseries",
   "description": "Утилизация CPU",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}